In [43]:
import numpy as np

Basic Array Creation

In [8]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [13]:
a = [1, 3, 3.5]
a

[1, 3, 3.5]

In [14]:
np.array(a)

array([1. , 3. , 3.5])

In [15]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Function

In [23]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr = np.arange(1, 11, 2)
arr

array([1, 3, 5, 7, 9])

In [33]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [34]:
arr = np.zeros((4, 6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [35]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [36]:
arr = np.ones((4, 6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [37]:
arr = np.linspace(1, 5, 2)
arr

array([1., 5.])

In [39]:
arr = np.linspace(1, 5, 3)
arr

array([1., 3., 5.])

In [48]:
arr = np.linspace(1, 5, 10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [49]:
arr = np.linspace(1, 5, 100)
arr

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

Random Number Generation

In [54]:
np.random.rand(5)

array([0.44558798, 0.38662454, 0.82207923, 0.98550306, 0.82894465])

In [55]:
np.random.rand(10)

array([0.154704  , 0.06610706, 0.31976419, 0.23323673, 0.70972364,
       0.53576345, 0.05253869, 0.71023874, 0.25619371, 0.72925851])

In [59]:
np.random.randn(10)

array([-0.75488527,  1.90050959, -0.79593674,  0.90436028,  1.36900364,
        0.01289409, -0.81988007,  0.12142322,  0.08744407,  1.26105261])

In [67]:
np.random.randint(5)

4

In [74]:
np.random.randint(10, 20, 10)

array([11, 15, 10, 10, 12, 14, 17, 11, 16, 19], dtype=int32)

Array Attributes

In [90]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr.shape # will give the shape of the matrix

(3, 3)

In [77]:
arr.size # will give the all numbers of element in the matrix

9

In [124]:
arr.dtype

dtype('int64')

Array Methods

In [92]:
arr.min() # will give minimum value from the matrix

np.int64(1)

In [98]:
arr.max() # will give maximum value from the matrix

np.int64(9)

In [99]:
arr.sum()

np.int64(45)

In [97]:
sum = int(arr.sum())
print(sum)

45


In [100]:
np.sum(arr, axis= 0) # column sum

array([12, 15, 18])

In [126]:
np.sum(arr, axis = 1) # row sum

array([ 15,  40,  65,  90, 115, 140])

In [127]:
arr.mean() # average

np.float64(15.5)

In [103]:
arr.std() # standered deviation

np.float64(2.581988897471611)

In [104]:
arr.argmax() # max element at which index

np.int64(8)

In [106]:
arr.argmin() # min element at which index

np.int64(0)

Reshaping and Resizing

In [112]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [122]:
arr = arr.reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [131]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])