In [81]:
import numpy as np

## Array Operation :

#### Arithemetics Operations

In [19]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])
a1, a2

(array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [23]:
a1 + a2 # size of both array should be always same

array([ 7,  9, 11, 13, 15])

In [24]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [25]:
a2 - a1

array([5, 5, 5, 5, 5])

In [26]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [27]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [28]:
a1 // a2

array([0, 0, 0, 0, 0])

In [29]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

#### Broadcasting

In [34]:
l  = [10, 20, 30, 40, 50]
arr = np.array(l)

In [37]:
arr + 10 # will add 10 in all elements of list l

array([20, 30, 40, 50, 60])

In [39]:
arr * 1.2 # as bonus

array([12., 24., 36., 48., 60.])

In [42]:
arr2 = np.arange(1, 26).reshape(5, 5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [44]:
arr2 + 10 # we can add 10 to the matrix as well

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [46]:
arr2 * 10 # can multiply by 10 to all elements of array or matrics

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150],
       [160, 170, 180, 190, 200],
       [210, 220, 230, 240, 250]])

#### Deep and Shallow Copy

In [53]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [57]:
slice1_5 = a[0: 5]
slice1_5

array([1, 2, 3, 4, 5])

In [59]:
slice1_5 = a[0: 5]
slice1_5 = slice1_5 * 10
slice1_5

array([10, 20, 30, 40, 50])

In [60]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [65]:
a[4 : 6]

array([5, 6])

In [67]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [68]:
b = a
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [70]:
b[0] = 99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [72]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [74]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [76]:
b = a.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [77]:
b = a * 10
b

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200])

In [78]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

#### Matrix Operations

In [83]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [84]:
A

array([[1, 2],
       [3, 4]])

In [85]:
B

array([[5, 6],
       [7, 8]])

In [86]:
A @ B

array([[19, 22],
       [43, 50]])

In [87]:
np.dot(A, B) # same use, use to multiply two metrics, same as @

array([[19, 22],
       [43, 50]])

In [88]:
A.T # use to transpose the metrics

array([[1, 3],
       [2, 4]])

### Advance Array Manipulations :

#### Stacking Array

In [90]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [91]:
A

array([[1, 2],
       [3, 4]])

In [93]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
# we can not stack two metrics

In [95]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [97]:
np.vstack((a, b)) # vertical stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [98]:
np.hstack((a, b)) # horizontal stack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [99]:
np.column_stack((a, b)) # column stack

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

#### Splitting Array

In [113]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [117]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [119]:
np.hsplit(c, 4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [118]:
np.vsplit(c, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [120]:
np.vsplit(c, 4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]