In [1]:
import numpy as np

NumPy Indexing and Slicing of Vectors

In [70]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [77]:
for i in arr:
    i += 1
print(arr[0])

11


In [73]:
arr[1]

np.int64(12)

In [15]:
arr[2]

np.int64(13)

In [16]:
arr[9]

np.int64(20)

In [19]:
arr[0 : 10] # slicing

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
arr[1 : 5] # slicing

array([12, 13, 14, 15])

In [23]:
arr[3 : ]

array([14, 15, 16, 17, 18, 19, 20])

In [24]:
arr[1 : 10 : 3]

array([12, 15, 18])

In [25]:
arr[1 : : 2]

array([12, 14, 16, 18, 20])

NumPy Indexing and Slicing of Matrix

In [80]:
arr = np.arange(1, 31).reshape(6, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [81]:
arr[0] # row slicing through indexing

array([1, 2, 3, 4, 5])

In [82]:
arr[4]

array([21, 22, 23, 24, 25])

In [83]:
arr[0, 0]

np.int64(1)

In [84]:
arr[0, 4]

np.int64(5)

In [85]:
arr[5, 0]

np.int64(26)

In [86]:
arr[5, 4]

np.int64(30)

In [87]:
slice_2378 = arr[0:2, 1:3]
slice_2378

array([[2, 3],
       [7, 8]])

In [88]:
slice_192024252930 = arr[3:6, 3:5]
slice_192024252930

array([[19, 20],
       [24, 25],
       [29, 30]])

In [45]:
slice_192024252930 = arr[3:, 3:]
slice_192024252930

array([[19, 20],
       [24, 25],
       [29, 30]])

In [49]:
arr[:, 2] # will get a column at coulmn index 1

array([ 3,  8, 13, 18, 23, 28])

In [53]:
arr[:, 4]

array([ 5, 10, 15, 20, 25, 30])

In [54]:
arr[:, 1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23],
       [27, 28]])

In [55]:
arr[:, 1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

Boolean Indexing

In [57]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [59]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [60]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])