##### Valid Sudoku

In [160]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [176]:
s.sum()

np.int64(405)

In [181]:
b = np.sum(s, axis = 1) # sum of all column elements
for i in b:
    if i != 45:
        print("suduko is not valid")
else :
        print("suduko is valid")

suduko is valid


In [182]:
c = np.sum(s, axis = 0) # sum of all row elements
for i in c:
    if i != 45:
        print("suduko is not valid")
else :
    print("suduko is valid")

suduko is valid


In [191]:
for i in range(0, 9, 3):
    for j in range(0, 9, 3):
        n = s[i:i+3, j:j+3]
        n.sum
        print(n.sum())

45
45
45
45
45
45
45
45
45


### General Questions

In [17]:
import numpy as np

In [18]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

##### Get the shape of the matrix.

In [19]:
data.shape

(5, 3)

##### Find the average age of students.

In [30]:
slice = data[:, 0]
slice

array([18, 19, 17, 18, 20])

In [31]:
slice.mean()

np.float64(18.4)

### OR

In [28]:
avg_age = data[:, 0].mean()
print(avg_age)

18.4


##### Extract Math marks of all students.

In [57]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [134]:
maths = data[:, 1]
maths

array([85, 92, 76, 65, 90])

### OR

In [135]:
maths_marks = data[:, 1]
print(maths_marks)

[85 92 76 65 90]


##### Find the highest Science mark.

In [104]:
science = data[0 : 5, 2]
science

array([78, 88, 95, 70, 85])

In [136]:
science.max()

np.int64(95)

### OR

In [139]:
highest_science = data[:, 2].max()
print(highest_science)

95


##### Get details of the student who scored more than 90 in Math.

In [80]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [35]:
student = data[data[:, 1] > 90]
print(student)

[[19 92 88]]


##### Increase Math marks of all students by 5.

In [15]:
maths_5 = data[:, 1] + 5
print(maths_5)

[90 97 81 70 95]


##### Find how many students are younger than 19.

In [111]:
age = data[:, 0]
age

array([18, 19, 17, 18, 20])

In [112]:
count = 0
for i in age:
    if i < 19:
        count += 1
print(count)

3


### OR

In [34]:
age_less_than_19 = (data[:, 0] < 19).sum()
print(age_less_than_19)

3


##### Calculate the average marks in each subject (column-wise mean).

In [151]:
marks_maths = data[:, 1]
marks_science = data[:, 2]
marks_maths
marks_science

array([78, 88, 95, 70, 85])

In [152]:
print(marks_maths.mean())
print(marks_science.mean())

81.6
83.2


### OR

In [154]:
avg_marks = data[:, 1:3].mean(axis=0)
print(avg_marks)

[81.6 83.2]


##### Get data of students who scored at least 80 in both subjects.

In [8]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])

In [217]:
students_both = data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]
print(students_both)

[[19 92 88]
 [20 90 85]]


##### Replace all Science marks < 75 with 0.

In [9]:
data[data[:, 2] < 75, 2] = 0
print(data)

[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18 65  0]
 [20 90 85]]


##### find the all values of elements of the matrics s

In [37]:
s = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
s

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
for i in range(3):
    for j in range(3):
        print(s[i][j])

1
2
3
4
5
6
7
8
9
